### ISSUE TITLE
How to reslove 'RuntimeError: Parentheses not matching!'

### ISSUE THREAD

**Issue by Jaroan** [yongchao98/NL2TL#1]
I had this input

`If ( prop_1 ) is not complete and time is greater than 20 units , then stop ( prop_2 ) and start ( prop_1 )`

The predicted TL is:

`( negation prop_1 and ( prop_2 and prop_1 ) )`

The corrected TL is:

`( future [20, infinity] (negation ( prop_1 ))) and ( negation ( prop_2 ) and ( prop_1 ) )`

But I got this error, and I'm unable to solve it:

> **RuntimeError: Parentheses not matching!**

Any suggestions are appreciated, thank you!

**Comment by yongchao98** [comment]
Hello Jaroan, thanks for your helpful comments. 

Here we divide each token with the space. Hence, there should be extra space between '(negation' and ')))'. Meanwhile, the 'future' syntax here should be replaced as 'finally'. And due to some limitation, each 'prop_i' should appear only once, so 'prop_1' can not appear twice here.

The correct format that can be regarded as syntactic correct is '( finally [20,infinite] ( negation ( prop_1 ) ) ) and ( negation ( prop_2 ) and ( prop_3 ) )'

Note that I have replaced 'prop_1' with 'prop_3', which may have different semantic meanings to your original sentence. Thus, you may change your input natural sentence in this case.

Sorry for the inconvenience to you and thanks for your help!

Best,
Yongchao

**Comment by Jaroan** [comment]
Hi Yongchao, thank you so much for the input!
I noticed my errors late and corrected the rest.
