### ISSUE TITLE
Questions about model import

### ISSUE THREAD

**Issue by ChaselLau666** [yongchao98/NL2TL#2]
thank you for your great work When I ran the RUN program I downloaded the weights file and saved it locally but I ran into this problem
![image](https://github.com/yongchao98/NL2TL/assets/139679124/f0d2ddb2-76c1-4534-9721-962f6d0aa0ce)

**Comment by yongchao98** [comment]
Hello,

Thanks for your try and question. It seems your downloaded directory lacks the files. It usually happens since the files are large. Maybe you can enter this directory https://drive.google.com/drive/folders/1vSaKOunMPA3uiOdx6IDbe-gmfREXQ9uO?usp=sharing    And then download all the items one by one, and move them to the same directory. 

Best,
Yongchao

**Comment by ChaselLau666** [comment]
Thank you for your help
